apiVersion: v1
kind: Service
metadata:
  name: {{ template "seaweedfs.name" . }}-filer
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "seaweedfs.name" . }}
    component: filer
spec:
  clusterIP: None
  ports:
  - name: "swfs-filer"
    port: {{ .Values.filer.port }}
    targetPort: {{ .Values.filer.port }}
    protocol: TCP
  - name: "swfs-filer-grpc"
    port: {{ .Values.filer.grpcPort }}
    targetPort: {{ .Values.filer.grpcPort }}
    protocol: TCP
{{- if .Values.filer.metricsPort }}
  - name: "swfs-filer-metrics"
    port: {{ .Values.filer.metricsPort }}
    targetPort: {{ .Values.filer.metricsPort }}
    protocol: TCP
{{- end }}
  selector:
    app: {{ template "seaweedfs.name" . }}
    component: filer