apiVersion: v1
kind: Service
metadata:
  name: {{ template "seaweedfs.name" . }}-s3
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "seaweedfs.name" . }}
    component: s3
spec:
  ports:
  - name: "swfs-s3"
    port: {{ .Values.s3.port }}
    targetPort: {{ .Values.s3.port }}
    protocol: TCP
  selector:
    app: {{ template "seaweedfs.name" . }}
    component: s3