apiVersion: v1
kind: Service
metadata:
  name: {{ template "seaweedfs.name" . }}-s3
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "seaweedfs.name" . }}
    component: s3
spec:
  ports:
  - name: "swfs-s3"
    port: {{ if .Values.s3.enabled }}{{ .Values.s3.port }}{{ else }}{{ .Values.filer.s3.port }}{{ end }}
    targetPort: {{ if .Values.s3.enabled }}{{ .Values.s3.port }}{{ else }}{{ .Values.filer.s3.port }}{{ end }}
    protocol: TCP
{{- if and .Values.s3.enabled .Values.s3.metricsPort }}
  - name: "metrics"
    port: {{ .Values.s3.metricsPort }}
    targetPort: {{ .Values.s3.metricsPort }}
    protocol: TCP
{{- end }}
  selector:
    app: {{ template "seaweedfs.name" . }}
    component: {{ if .Values.s3.enabled }}s3{{ else }}filer{{ end }}
