apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-seaweedfs-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
stringData:
  user: "YourSWUser"
  password: "HardCodedPassword"
  # better to random generate and create in DB
  # password: {{ randAlphaNum 10 | sha256sum | b64enc | trunc 32 }}
