{{- if .Values.defaultSettings.registrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.defaultSettings.registrySecret }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "secret" . }}
{{- end }}
