#!/bin/bash


# preprare
# command -v yq > /dev/null || pip install yq
# stage changed
git add -u

echo "## Charts"  > LIST.md
echo >> LIST.md
echo "| Name | Version | AppVersion |"  >> LIST.md
echo "|------|---------|------------|"  >> LIST.md

for chart in */Chart.yaml; do
  name=$(dirname $chart)

  mkdir -p charts/$name
  [ ! -f $name/README.md ] || cp $name/README.md charts/$name

  echo "| $(yq r $chart 'name') | $(yq r $chart 'version') | $(yq r $chart 'appVersion') |" >> LIST.md

  # changed
  git diff --quiet --staged master -- $name || {
    echo "| $(yq r $chart 'name') | $(yq r $chart 'version') | $(yq r $chart 'appVersion') | $(date +"%Y-%m-%d %H:%M:%S") |" >> CHANGELOG.md
  }
done


echo >> LIST.md
echo "## wener/charts"  >> LIST.md
echo >> LIST.md
echo "| Name | Version | AppVersion |"  >> LIST.md
echo "|------|---------|------------|"  >> LIST.md

for chart in wener/charts/*/Chart.yaml; do
  name=$(dirname $chart | xargs basename)
  echo "| $(yq r $chart 'name') | $(yq r $chart 'version') | $(yq r $chart 'appVersion') |" >> LIST.md
done

cat README.raw.md LIST.md > README.md
