#!/bin/bash

sync-chart() {
  local OPTIND o
  local repo url chart verbose= dry wdir
  while getopts 'r:u:c:w:Vnh' o; do
    case $o in
      r)
        repo="$OPTARG";;
      u)
        url="$OPTARG";;
      c)
        chart="$OPTARG";;
      w)
        wdir="$OPTARG";;
      C)
        check=;;
      V)
        verbose=1;;
      n)
        dry=1;;
      h|?)
        _sync-chart-usage;;
    esac
  done
  shift $((OPTIND - 1))
  [[ $# != 2 && $# != 0 ]] && {
    echo "unexpected params ($#): $@"
    return 1
  }
  [ $# = 2 ] && {
    chart=$1
    url=$2
  }

  [ -n "$wdir" ] && cd $wdir

  local exp_ver act_ver=""
  # show chart will read cwd chart
  exp_ver=$(cd /tmp; helm show chart $chart --repo $url | yq r - version)
  [ -e charts/$chart-$exp_ver.tgz ] && {
    echo "chart $chart-$exp_ver already exists"
    return 0
  }
  
  [ -f $chart/Chart.yaml ] && act_ver=$(yq r $chart/Chart.yaml version)

  [ "$exp_ver" = "$act_ver" ] && {
    echo "chart $chart-$exp_ver unchanged"
    return 0
  }
  
  [ -e $chart ] && {
    echo "remove $chart-$act_ver"
    rm -rf $chart
  }

  echo "sync $chart-$exp_ver"
  helm pull --untar $chart --repo $url
  
  # empty dir
  rm -rf $chart-$exp_ver.tgz

  # echo "package $chart-$exp_ver"
  # helm package -d dist $chart
}

_sync-chart-usage() {
  echo "sync-chart [-ruchv] [chart] [repo]
  -u  repo url
  -c  chart name
  -w  work dir
  -V  verbose
  -v  dry run
  -h  show this message
"
}

if [ $(basename $0) = "sync-chart" ]; then
  set -e
  sync-chart "$@"
fi
